# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zen_data_svr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zen_data_svr.proto',
  package='zen_data_svr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12zen_data_svr.proto\x12\x0czen_data_svr\"\xaf\x01\n\x0cPushKlineReq\x12\n\n\x02ts\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08sec_type\x18\x0b \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\x0c\n\x04high\x18\x05 \x01(\x01\x12\x0b\n\x03low\x18\x06 \x01(\x01\x12\r\n\x05\x63lose\x18\x07 \x01(\x01\x12\x0b\n\x03vol\x18\x08 \x01(\x03\x12\x0e\n\x06\x61mount\x18\t \x01(\x01\x12\x0e\n\x06is_end\x18\n \x01(\x05\"/\n\x0cPushKlineRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"]\n\x0b\x41skKlineReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\t\x12\x10\n\x08sec_type\x18\x03 \x01(\t\x12\x0f\n\x07\x66rom_ts\x18\x04 \x01(\x05\x12\r\n\x05to_ts\x18\x05 \x01(\x05\"x\n\x05Kline\x12\n\n\x02ts\x18\x01 \x01(\x05\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0b\n\x03vol\x18\x06 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x01\x12\x0e\n\x06is_end\x18\x08 \x01(\x05\"\x83\x01\n\x0b\x41skKlineRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0e\n\x06period\x18\x04 \x01(\t\x12\x10\n\x08sec_type\x18\x05 \x01(\t\x12#\n\x06klines\x18\x06 \x03(\x0b\x32\x13.zen_data_svr.Kline2\xa2\x01\n\rZendataHandle\x12I\n\rPushKlineData\x12\x1a.zen_data_svr.PushKlineReq\x1a\x1a.zen_data_svr.PushKlineRsp\"\x00\x12\x46\n\x0c\x41skKlineData\x12\x19.zen_data_svr.AskKlineReq\x1a\x19.zen_data_svr.AskKlineRsp\"\x00\x62\x06proto3'
)




_PUSHKLINEREQ = _descriptor.Descriptor(
  name='PushKlineReq',
  full_name='zen_data_svr.PushKlineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='zen_data_svr.PushKlineReq.ts', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_data_svr.PushKlineReq.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_type', full_name='zen_data_svr.PushKlineReq.sec_type', index=2,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_data_svr.PushKlineReq.period', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='zen_data_svr.PushKlineReq.open', index=4,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='zen_data_svr.PushKlineReq.high', index=5,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='zen_data_svr.PushKlineReq.low', index=6,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='zen_data_svr.PushKlineReq.close', index=7,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vol', full_name='zen_data_svr.PushKlineReq.vol', index=8,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='zen_data_svr.PushKlineReq.amount', index=9,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_end', full_name='zen_data_svr.PushKlineReq.is_end', index=10,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=212,
)


_PUSHKLINERSP = _descriptor.Descriptor(
  name='PushKlineRsp',
  full_name='zen_data_svr.PushKlineRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zen_data_svr.PushKlineRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zen_data_svr.PushKlineRsp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=261,
)


_ASKKLINEREQ = _descriptor.Descriptor(
  name='AskKlineReq',
  full_name='zen_data_svr.AskKlineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_data_svr.AskKlineReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_data_svr.AskKlineReq.period', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_type', full_name='zen_data_svr.AskKlineReq.sec_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_ts', full_name='zen_data_svr.AskKlineReq.from_ts', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_ts', full_name='zen_data_svr.AskKlineReq.to_ts', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=356,
)


_KLINE = _descriptor.Descriptor(
  name='Kline',
  full_name='zen_data_svr.Kline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='zen_data_svr.Kline.ts', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='zen_data_svr.Kline.open', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='zen_data_svr.Kline.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='zen_data_svr.Kline.low', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='zen_data_svr.Kline.close', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vol', full_name='zen_data_svr.Kline.vol', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='zen_data_svr.Kline.amount', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_end', full_name='zen_data_svr.Kline.is_end', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=478,
)


_ASKKLINERSP = _descriptor.Descriptor(
  name='AskKlineRsp',
  full_name='zen_data_svr.AskKlineRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zen_data_svr.AskKlineRsp.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zen_data_svr.AskKlineRsp.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='zen_data_svr.AskKlineRsp.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='zen_data_svr.AskKlineRsp.period', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_type', full_name='zen_data_svr.AskKlineRsp.sec_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='klines', full_name='zen_data_svr.AskKlineRsp.klines', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=612,
)

_ASKKLINERSP.fields_by_name['klines'].message_type = _KLINE
DESCRIPTOR.message_types_by_name['PushKlineReq'] = _PUSHKLINEREQ
DESCRIPTOR.message_types_by_name['PushKlineRsp'] = _PUSHKLINERSP
DESCRIPTOR.message_types_by_name['AskKlineReq'] = _ASKKLINEREQ
DESCRIPTOR.message_types_by_name['Kline'] = _KLINE
DESCRIPTOR.message_types_by_name['AskKlineRsp'] = _ASKKLINERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushKlineReq = _reflection.GeneratedProtocolMessageType('PushKlineReq', (_message.Message,), {
  'DESCRIPTOR' : _PUSHKLINEREQ,
  '__module__' : 'zen_data_svr_pb2'
  # @@protoc_insertion_point(class_scope:zen_data_svr.PushKlineReq)
  })
_sym_db.RegisterMessage(PushKlineReq)

PushKlineRsp = _reflection.GeneratedProtocolMessageType('PushKlineRsp', (_message.Message,), {
  'DESCRIPTOR' : _PUSHKLINERSP,
  '__module__' : 'zen_data_svr_pb2'
  # @@protoc_insertion_point(class_scope:zen_data_svr.PushKlineRsp)
  })
_sym_db.RegisterMessage(PushKlineRsp)

AskKlineReq = _reflection.GeneratedProtocolMessageType('AskKlineReq', (_message.Message,), {
  'DESCRIPTOR' : _ASKKLINEREQ,
  '__module__' : 'zen_data_svr_pb2'
  # @@protoc_insertion_point(class_scope:zen_data_svr.AskKlineReq)
  })
_sym_db.RegisterMessage(AskKlineReq)

Kline = _reflection.GeneratedProtocolMessageType('Kline', (_message.Message,), {
  'DESCRIPTOR' : _KLINE,
  '__module__' : 'zen_data_svr_pb2'
  # @@protoc_insertion_point(class_scope:zen_data_svr.Kline)
  })
_sym_db.RegisterMessage(Kline)

AskKlineRsp = _reflection.GeneratedProtocolMessageType('AskKlineRsp', (_message.Message,), {
  'DESCRIPTOR' : _ASKKLINERSP,
  '__module__' : 'zen_data_svr_pb2'
  # @@protoc_insertion_point(class_scope:zen_data_svr.AskKlineRsp)
  })
_sym_db.RegisterMessage(AskKlineRsp)



_ZENDATAHANDLE = _descriptor.ServiceDescriptor(
  name='ZendataHandle',
  full_name='zen_data_svr.ZendataHandle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=615,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushKlineData',
    full_name='zen_data_svr.ZendataHandle.PushKlineData',
    index=0,
    containing_service=None,
    input_type=_PUSHKLINEREQ,
    output_type=_PUSHKLINERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AskKlineData',
    full_name='zen_data_svr.ZendataHandle.AskKlineData',
    index=1,
    containing_service=None,
    input_type=_ASKKLINEREQ,
    output_type=_ASKKLINERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZENDATAHANDLE)

DESCRIPTOR.services_by_name['ZendataHandle'] = _ZENDATAHANDLE

# @@protoc_insertion_point(module_scope)
