# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import zen_data_svr_pb2 as zen__data__svr__pb2


class ZendataHandleStub(object):
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushKlineData = channel.unary_unary(
                '/zen_data_svr.ZendataHandle/PushKlineData',
                request_serializer=zen__data__svr__pb2.PushKlineReq.SerializeToString,
                response_deserializer=zen__data__svr__pb2.PushKlineRsp.FromString,
                )
        self.AskKlineData = channel.unary_unary(
                '/zen_data_svr.ZendataHandle/AskKlineData',
                request_serializer=zen__data__svr__pb2.AskKlineReq.SerializeToString,
                response_deserializer=zen__data__svr__pb2.AskKlineRsp.FromString,
                )


class ZendataHandleServicer(object):
    """
    """

    def PushKlineData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskKlineData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZendataHandleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushKlineData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushKlineData,
                    request_deserializer=zen__data__svr__pb2.PushKlineReq.FromString,
                    response_serializer=zen__data__svr__pb2.PushKlineRsp.SerializeToString,
            ),
            'AskKlineData': grpc.unary_unary_rpc_method_handler(
                    servicer.AskKlineData,
                    request_deserializer=zen__data__svr__pb2.AskKlineReq.FromString,
                    response_serializer=zen__data__svr__pb2.AskKlineRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zen_data_svr.ZendataHandle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZendataHandle(object):
    """
    """

    @staticmethod
    def PushKlineData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zen_data_svr.ZendataHandle/PushKlineData',
            zen__data__svr__pb2.PushKlineReq.SerializeToString,
            zen__data__svr__pb2.PushKlineRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AskKlineData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zen_data_svr.ZendataHandle/AskKlineData',
            zen__data__svr__pb2.AskKlineReq.SerializeToString,
            zen__data__svr__pb2.AskKlineRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
